### ISSUE TITLE
Cannot change status of Pump i2d

### ISSUE THREAD

**Issue by Fvanoost** [CLARENNE-Q/iaqualink_iqpump01#3]
## 🐞 Bug Report

Thanks for reporting a bug! Please fill out this form so we can understand the issue and help resolve it.

---

### 🔧 Home Assistant Version : `2025.4.3'

---

### 📦 Integration Version `1.0.3`

---

### 🌀 Pump Model or Controller : Zodiac iQPUMP iAqualink control

---

### ⚠️ Error Message

_If you see an error in the UI or logs, copy/paste it here._

After integration 1 device (Pump i2d) and 4 entities shows up (Pump Speed, Pump i2d, Pump RPM Target, Pump Power)

If I use the mobile app, I can start/stop the pump, change the speed... and all info is reflected in the device and entities

<img width="413" alt="Image" src="https://github.com/user-attachments/assets/fd5065c6-4b33-4f18-9d6c-367d9252cbe8" />

Lot's of info are in the device 

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/80c3b16a-621a-48a4-a750-0e59e244c61e" />

I can stop the pump BUT I can not start it again from HA

some logs hereafter : 
2025-04-29 17:53:35.587 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [546608639152] Initialized trigger
2025-04-29 17:53:46.432 DEBUG (SyncWorker_7) [custom_components.iaqualink_iqpump01.api] [refresh_data] Refreshing pump data...
2025-04-29 17:53:47.138 DEBUG (SyncWorker_7) [custom_components.iaqualink_iqpump01.api] [refresh_data] Response: {"requestID":"","alldata":{"fwversion":"6.1.119","serialnumber":"QSF5YUNW67VC","updateprogress":"0/0","updateflag":"0","runstate":"off","rpmtarget":"2775","utctime":"2025-04-29 15:53:46","timezone":"Europe/Madrid","localtime":"2025-04-29 17:53:46","wifistatus":{"state":"connected","ssid":"Banya"},"hotspottimer":"4291841240","currentspan":"-1","opmode":"0","timeoutperiod":"10800","timeouttimer":"-1","countdownperiod":"10800","countdowntimer":"-1","countdownrpm":"2750","quickcleanrpm":"3450","quickcleanperiod":"1800","quickcleantimer":"-1","customspeedtimer":"-1","customspeedrpm":"2775","globalrpmmin":"600","globalrpmmax":"3450","demandvisible":"1","faultvisible":"0","busstatus":"1","freezeprotectsetpointc":"3","freezeprotectperiod":"1800","freezeprotectrpm":"1000","freezeprotectstatus":"0","freezeprotectenable":"1","primingrpm":"2750","primingperiod":"180","primingtimer":"-1","motordata":{"speed":"0","power":"0","temperature":"23","productid":"17","horsepower":"","horsepowercode":""}}}
2025-04-29 17:53:47.138 DEBUG (SyncWorker_8) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:53:47.138 DEBUG (SyncWorker_6) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:53:47.139 DEBUG (SyncWorker_9) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:53:47.140 DEBUG (MainThread) [custom_components.iaqualink_iqpump01.number] [PumpSpeedNumber] Raw API data: {'fwversion': '6.1.119', 'serialnumber': 'QSF5YUNW67VC', 'updateprogress': '0/0', 'updateflag': '0', 'runstate': 'off', 'rpmtarget': '2775', 'utctime': '2025-04-29 15:53:46', 'timezone': 'Europe/Madrid', 'localtime': '2025-04-29 17:53:46', 'wifistatus': {'state': 'connected', 'ssid': 'Banya'}, 'hotspottimer': '4291841240', 'currentspan': '-1', 'opmode': '0', 'timeoutperiod': '10800', 'timeouttimer': '-1', 'countdownperiod': '10800', 'countdowntimer': '-1', 'countdownrpm': '2750', 'quickcleanrpm': '3450', 'quickcleanperiod': '1800', 'quickcleantimer': '-1', 'customspeedtimer': '-1', 'customspeedrpm': '2775', 'globalrpmmin': '600', 'globalrpmmax': '3450', 'demandvisible': '1', 'faultvisible': '0', 'busstatus': '1', 'freezeprotectsetpointc': '3', 'freezeprotectperiod': '1800', 'freezeprotectrpm': '1000', 'freezeprotectstatus': '0', 'freezeprotectenable': '1', 'primingrpm': '2750', 'primingperiod': '180', 'primingtimer': '-1', 'motordata': {'speed': '0', 'power': '0', 'temperature': '23', 'productid': '17', 'horsepower': '', 'horsepowercode': ''}}
2025-04-29 17:54:13.877 DEBUG (SyncWorker_9) [custom_components.iaqualink_iqpump01.api] [_send_command] POST /opmode/write | value=0
2025-04-29 17:54:14.338 DEBUG (SyncWorker_9) [custom_components.iaqualink_iqpump01.api] [_send_command] Response: {"requestID":"","opmode":{"operation":"write","value":"0"}}
2025-04-29 17:54:14.339 DEBUG (SyncWorker_6) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:54:16.433 DEBUG (SyncWorker_6) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:54:16.434 DEBUG (SyncWorker_9) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:54:16.435 DEBUG (SyncWorker_11) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:54:16.435 DEBUG (SyncWorker_7) [custom_components.iaqualink_iqpump01.api] [refresh_data] Using cached pump data.
2025-04-29 17:54:16.435 DEBUG (MainThread) [custom_components.iaqualink_iqpump01.number] [PumpSpeedNumber] Raw API data: {'fwversion': '6.1.119', 'serialnumber': 'QSF5YUNW67VC', 'updateprogress': '0/0', 'updateflag': '0', 'runstate': 'off', 'rpmtarget': '2775', 'utctime': '2025-04-29 15:53:46', 'timezone': 'Europe/Madrid', 'localtime': '2025-04-29 17:53:46', 'wifistatus': {'state': 'connected', 'ssid': 'Banya'}, 'hotspottimer': '4291841240', 'currentspan': '-1', 'opmode': '0', 'timeoutperiod': '10800', 'timeouttimer': '-1', 'countdownperiod': '10800', 'countdowntimer': '-1', 'countdownrpm': '2750', 'quickcleanrpm': '3450', 'quickcleanperiod': '1800', 'quickcleantimer': '-1', 'customspeedtimer': '-1', 'customspeedrpm': '2775', 'globalrpmmin': '600', 'globalrpmmax': '3450', 'demandvisible': '1', 'faultvisible': '0', 'busstatus': '1', 'freezeprotectsetpointc': '3', 'freezeprotectperiod': '1800', 'freezeprotectrpm': '1000', 'freezeprotectstatus': '0', 'freezeprotectenable': '1', 'primingrpm': '2750', 'primingperiod': '180', 'primingtimer': '-1', 'motordata': {'speed': '0', 'power': '0', 'temperature': '23', 'productid': '17', 'horsepower': '', 'horsepowercode': ''}}

**Comment by Fvanoost** [comment]
one additional info. In the Logbook, I see : "Pump i2d turned off triggered by action Switch: Turn on"

**Comment by CLARENNE-Q** [comment]
Hi there! 👋

Thanks for your feedback. I wanted to clarify an important detail about how the ON/OFF switch (switch.pump_i2d) works in Home Assistant:

🟢 What the ON button does

When you turn the pump ON in Home Assistant, it sends this command:

`POST /opmode/write | value=0`

This does not force a manual start — instead, it behaves like the "Resume Scheduled Operation" button in the mobile app. In other words, it only works if a timer is currently active.

    ✅ For example: if you're outside of any active timer period, turning the pump ON in Home Assistant won’t start it — and that’s expected behavior.

🔴 What the OFF button does

Turning the pump OFF sends a stop command (opmode=2), which immediately stops the pump, regardless of any timers.

❓ Can you confirm:

Do you have an active timer during the time you try to restart the pump from Home Assistant?
You can check this in the mobile app. If there's no timer covering that period, pressing ON in HA won't have any effect.

🛠️ If you'd like to force a manual pump start from Home Assistant, just let us know — i will working on adding that feature! 😊

**Comment by Fvanoost** [comment]
OK, thanks a lot and it makes sense for me. There was no active timer during the test yesterday. I will create a 24h program (always ON) and use HA to stop when it's not needed anymore and revert to you

Would be amazing indeed to be able to control the start of the pump from HA without the need to use the app. If you need any help, let me know

**Comment by microbmen** [comment]
Thanks for the project.  

I cant get it to work either.  I tried a few things with no luck. 

The slider defaults to 0 - 100, and perhaps the API knows it cant receive under 600 RPM.   I modified the slider to accept 600 - 3450, which fixed the UI, however then in the logs im getting an error expecting 0-100.  
Further, whatever the current running RPMs are , i.e. 2000.  The slider will display 2000 as the maximum value.  Producing a false limit to whatever the current running RPMS are.

**Comment by microbmen** [comment]
Yes.  It is showing 0-100% now.  It seems to be working. Just need to interpret % to RPMs in my head.  Which is fine.   Thank you.

**Comment by CLARENNE-Q** [comment]
Is it good for everybody like this ?

**Comment by microbmen** [comment]
Working well since last update.

**Comment by Fvanoost** [comment]
Hi, happy to hear that the issue raised by @microbmen has been resolved but this thread initially started from the need to be able to start/stop the pump from the plugin directly. @CLARENNE-Q , have you been able to make any progress there?

**Comment by Astroman** [comment]
I have the same question as Fvanoost and I'm confused by the solution to create a 24 hour schedule to enable starting the pump. Won't that restart the pump every 24 hours and prevent other schedules from stopping it?

**Comment by TheNetworker69** [comment]
> Est-ce que c'est bon pour tout le monde comme ça ?

Hello, Still not good for me; the speed doesn't change, the cursor systematically returns to the program's set speed.
